//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `HumanCameraBody.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <HumanCameraBody.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[2] =
{
    "::Ice::Object",
    "::RoboCompHumanCameraBody::HumanCameraBody"
};
const ::std::string iceC_RoboCompHumanCameraBody_HumanCameraBody_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newPeopleData"
};
const ::std::string iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name = "newPeopleData";

}

bool
RoboCompHumanCameraBody::HumanCameraBody::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompHumanCameraBody_HumanCameraBody_ids, iceC_RoboCompHumanCameraBody_HumanCameraBody_ids + 2, s);
}

::std::vector<::std::string>
RoboCompHumanCameraBody::HumanCameraBody::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[0], &iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[2]);
}

::std::string
RoboCompHumanCameraBody::HumanCameraBody::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompHumanCameraBody::HumanCameraBody::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompHumanCameraBody::HumanCameraBody";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompHumanCameraBody::HumanCameraBody::_iceD_newPeopleData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    PeopleData ret = this->newPeopleData(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompHumanCameraBody::HumanCameraBody::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompHumanCameraBody_HumanCameraBody_ops, iceC_RoboCompHumanCameraBody_HumanCameraBody_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompHumanCameraBody_HumanCameraBody_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newPeopleData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompHumanCameraBody::HumanCameraBodyPrx::_iceI_newPeopleData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompHumanCameraBody::PeopleData>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name);
    outAsync->invoke(iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompHumanCameraBody::HumanCameraBodyPrx::_newInstance() const
{
    return ::IceInternal::createProxy<HumanCameraBodyPrx>();
}
/// \endcond

const ::std::string&
RoboCompHumanCameraBody::HumanCameraBodyPrx::ice_staticId()
{
    return HumanCameraBody::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name = "newPeopleData";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompHumanCameraBody::upCast(HumanCameraBody* p) { return p; }

void
::IceProxy::RoboCompHumanCameraBody::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< HumanCameraBody>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new HumanCameraBody;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompHumanCameraBody::HumanCameraBody::_iceI_begin_newPeopleData(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompHumanCameraBody::PeopleData
IceProxy::RoboCompHumanCameraBody::HumanCameraBody::end_newPeopleData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompHumanCameraBody_HumanCameraBody_newPeopleData_name);
    ::RoboCompHumanCameraBody::PeopleData ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompHumanCameraBody::HumanCameraBody::_newInstance() const
{
    return new HumanCameraBody;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompHumanCameraBody::HumanCameraBody::ice_staticId()
{
    return ::RoboCompHumanCameraBody::HumanCameraBody::ice_staticId();
}

RoboCompHumanCameraBody::HumanCameraBody::~HumanCameraBody()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompHumanCameraBody::upCast(HumanCameraBody* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[2] =
{
    "::Ice::Object",
    "::RoboCompHumanCameraBody::HumanCameraBody"
};

}

bool
RoboCompHumanCameraBody::HumanCameraBody::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompHumanCameraBody_HumanCameraBody_ids, iceC_RoboCompHumanCameraBody_HumanCameraBody_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompHumanCameraBody::HumanCameraBody::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[0], &iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[2]);
}

const ::std::string&
RoboCompHumanCameraBody::HumanCameraBody::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompHumanCameraBody::HumanCameraBody::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompHumanCameraBody::HumanCameraBody";
    return typeId;
#else
    return iceC_RoboCompHumanCameraBody_HumanCameraBody_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompHumanCameraBody::HumanCameraBody::_iceD_newPeopleData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    PeopleData ret = this->newPeopleData(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompHumanCameraBody_HumanCameraBody_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newPeopleData"
};

}

/// \cond INTERNAL
bool
RoboCompHumanCameraBody::HumanCameraBody::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompHumanCameraBody_HumanCameraBody_all, iceC_RoboCompHumanCameraBody_HumanCameraBody_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompHumanCameraBody_HumanCameraBody_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newPeopleData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompHumanCameraBody::HumanCameraBody::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< HumanCameraBody, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompHumanCameraBody::HumanCameraBody::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HumanCameraBody, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompHumanCameraBody::_icePatchObjectPtr(HumanCameraBodyPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = HumanCameraBodyPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(HumanCameraBody::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
