//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Giraff.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Giraff_h__
#define __Giraff_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompGiraff
{

class Giraff;
class GiraffPrx;

}

namespace RoboCompGiraff
{

class HardwareFailedException : public ::Ice::UserExceptionHelper<HardwareFailedException, ::Ice::UserException>
{
public:

    virtual ~HardwareFailedException();

    HardwareFailedException(const HardwareFailedException&) = default;

    HardwareFailedException() = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    HardwareFailedException(const ::std::string& what) :
        what(::std::move(what))
    {
    }

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&> ice_tuple() const
    {
        return std::tie(what);
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    ::std::string what;
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

struct Botones
{
    int Rojo;
    int Verde;
    int Dial;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const int&, const int&, const int&> ice_tuple() const
    {
        return std::tie(Rojo, Verde, Dial);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompGiraff
{

class Giraff : public virtual ::Ice::Object
{
public:

    using ProxyType = GiraffPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual float decTilt(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_decTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual Botones getBotonesState(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getBotonesState(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual float getTilt(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual float incTilt(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_incTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void setTilt(float tilt, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_setTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompGiraff
{

class GiraffPrx : public virtual ::Ice::Proxy<GiraffPrx, ::Ice::ObjectPrx>
{
public:

    float decTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<float>(true, this, &GiraffPrx::_iceI_decTilt, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto decTiltAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<float>>().get_future())
    {
        return _makePromiseOutgoing<float, P>(false, this, &GiraffPrx::_iceI_decTilt, context);
    }

    ::std::function<void()>
    decTiltAsync(::std::function<void(float)> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<float>(response, ex, sent, this, &RoboCompGiraff::GiraffPrx::_iceI_decTilt, context);
    }

    /// \cond INTERNAL
    void _iceI_decTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<float>>&, const ::Ice::Context&);
    /// \endcond

    Botones getBotonesState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompGiraff::Botones>(true, this, &GiraffPrx::_iceI_getBotonesState, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getBotonesStateAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompGiraff::Botones>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompGiraff::Botones, P>(false, this, &GiraffPrx::_iceI_getBotonesState, context);
    }

    ::std::function<void()>
    getBotonesStateAsync(::std::function<void(::RoboCompGiraff::Botones)> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompGiraff::Botones>(response, ex, sent, this, &RoboCompGiraff::GiraffPrx::_iceI_getBotonesState, context);
    }

    /// \cond INTERNAL
    void _iceI_getBotonesState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGiraff::Botones>>&, const ::Ice::Context&);
    /// \endcond

    float getTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<float>(true, this, &GiraffPrx::_iceI_getTilt, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getTiltAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<float>>().get_future())
    {
        return _makePromiseOutgoing<float, P>(false, this, &GiraffPrx::_iceI_getTilt, context);
    }

    ::std::function<void()>
    getTiltAsync(::std::function<void(float)> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<float>(response, ex, sent, this, &RoboCompGiraff::GiraffPrx::_iceI_getTilt, context);
    }

    /// \cond INTERNAL
    void _iceI_getTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<float>>&, const ::Ice::Context&);
    /// \endcond

    float incTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<float>(true, this, &GiraffPrx::_iceI_incTilt, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto incTiltAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<float>>().get_future())
    {
        return _makePromiseOutgoing<float, P>(false, this, &GiraffPrx::_iceI_incTilt, context);
    }

    ::std::function<void()>
    incTiltAsync(::std::function<void(float)> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<float>(response, ex, sent, this, &RoboCompGiraff::GiraffPrx::_iceI_incTilt, context);
    }

    /// \cond INTERNAL
    void _iceI_incTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<float>>&, const ::Ice::Context&);
    /// \endcond

    void setTilt(float tilt, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &GiraffPrx::_iceI_setTilt, tilt, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setTiltAsync(float tilt, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &GiraffPrx::_iceI_setTilt, tilt, context);
    }

    ::std::function<void()>
    setTiltAsync(float tilt,
                 ::std::function<void()> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompGiraff::GiraffPrx::_iceI_setTilt, tilt, context);
    }

    /// \cond INTERNAL
    void _iceI_setTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, float, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    GiraffPrx() = default;
    friend ::std::shared_ptr<GiraffPrx> IceInternal::createProxy<GiraffPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::RoboCompGiraff::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompGiraff::HardwareFailedException& v)
    {
        istr->readAll(v.what);
    }
};

template<>
struct StreamableTraits<::RoboCompGiraff::Botones>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 12;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompGiraff::Botones, S>
{
    static void read(S* istr, ::RoboCompGiraff::Botones& v)
    {
        istr->readAll(v.Rojo, v.Verde, v.Dial);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompGiraff
{

using GiraffPtr = ::std::shared_ptr<Giraff>;
using GiraffPrxPtr = ::std::shared_ptr<GiraffPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompGiraff
{

class Giraff;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< Giraff>&);
::IceProxy::Ice::Object* upCast(Giraff*);
/// \endcond

}

}

namespace RoboCompGiraff
{

class Giraff;
/// \cond INTERNAL
::Ice::Object* upCast(Giraff*);
/// \endcond
typedef ::IceInternal::Handle< Giraff> GiraffPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGiraff::Giraff> GiraffPrx;
typedef GiraffPrx GiraffPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(GiraffPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompGiraff
{

class HardwareFailedException : public ::Ice::UserException
{
public:

    HardwareFailedException() {}
    /**
     * One-shot constructor to initialize all data members.
     */
    explicit HardwareFailedException(const ::std::string& what);
    virtual ~HardwareFailedException() throw();

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    virtual ::std::string ice_id() const;
    /**
     * Polymporphically clones this exception.
     * @return A shallow copy of this exception.
     */
    virtual HardwareFailedException* ice_clone() const;
    /**
     * Throws this exception.
     */
    virtual void ice_throw() const;

    ::std::string what;

protected:

    /// \cond STREAM
    virtual void _writeImpl(::Ice::OutputStream*) const;
    virtual void _readImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

struct Botones
{
    ::Ice::Int Rojo;
    ::Ice::Int Verde;
    ::Ice::Int Dial;

    bool operator==(const Botones& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(Rojo != rhs_.Rojo)
        {
            return false;
        }
        if(Verde != rhs_.Verde)
        {
            return false;
        }
        if(Dial != rhs_.Dial)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Botones& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(Rojo < rhs_.Rojo)
        {
            return true;
        }
        else if(rhs_.Rojo < Rojo)
        {
            return false;
        }
        if(Verde < rhs_.Verde)
        {
            return true;
        }
        else if(rhs_.Verde < Verde)
        {
            return false;
        }
        if(Dial < rhs_.Dial)
        {
            return true;
        }
        else if(rhs_.Dial < Dial)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Botones& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const Botones& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const Botones& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const Botones& rhs_) const
    {
        return !operator<(rhs_);
    }
};

}

namespace RoboCompGiraff
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_decTilt.
 */
class Callback_Giraff_decTilt_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Giraff_decTilt_Base> Callback_Giraff_decTiltPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_getBotonesState.
 */
class Callback_Giraff_getBotonesState_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Giraff_getBotonesState_Base> Callback_Giraff_getBotonesStatePtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_getTilt.
 */
class Callback_Giraff_getTilt_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Giraff_getTilt_Base> Callback_Giraff_getTiltPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_incTilt.
 */
class Callback_Giraff_incTilt_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Giraff_incTilt_Base> Callback_Giraff_incTiltPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_setTilt.
 */
class Callback_Giraff_setTilt_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Giraff_setTilt_Base> Callback_Giraff_setTiltPtr;

}

namespace IceProxy
{

namespace RoboCompGiraff
{

class Giraff : public virtual ::Ice::Proxy<Giraff, ::IceProxy::Ice::Object>
{
public:

    ::Ice::Float decTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_decTilt(_iceI_begin_decTilt(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_decTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_decTilt(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_decTilt(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_decTilt(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_decTilt(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_decTilt(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_decTilt(const ::RoboCompGiraff::Callback_Giraff_decTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_decTilt(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_decTilt(const ::Ice::Context& context, const ::RoboCompGiraff::Callback_Giraff_decTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_decTilt(context, cb, cookie);
    }

    ::Ice::Float end_decTilt(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_decTilt(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::RoboCompGiraff::Botones getBotonesState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getBotonesState(_iceI_begin_getBotonesState(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getBotonesState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getBotonesState(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBotonesState(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBotonesState(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBotonesState(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBotonesState(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBotonesState(const ::RoboCompGiraff::Callback_Giraff_getBotonesStatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBotonesState(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBotonesState(const ::Ice::Context& context, const ::RoboCompGiraff::Callback_Giraff_getBotonesStatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBotonesState(context, cb, cookie);
    }

    ::RoboCompGiraff::Botones end_getBotonesState(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getBotonesState(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::Ice::Float getTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getTilt(_iceI_begin_getTilt(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getTilt(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getTilt(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getTilt(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getTilt(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getTilt(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getTilt(const ::RoboCompGiraff::Callback_Giraff_getTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getTilt(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getTilt(const ::Ice::Context& context, const ::RoboCompGiraff::Callback_Giraff_getTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getTilt(context, cb, cookie);
    }

    ::Ice::Float end_getTilt(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getTilt(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::Ice::Float incTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_incTilt(_iceI_begin_incTilt(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_incTilt(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_incTilt(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_incTilt(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_incTilt(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_incTilt(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_incTilt(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_incTilt(const ::RoboCompGiraff::Callback_Giraff_incTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_incTilt(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_incTilt(const ::Ice::Context& context, const ::RoboCompGiraff::Callback_Giraff_incTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_incTilt(context, cb, cookie);
    }

    ::Ice::Float end_incTilt(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_incTilt(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void setTilt(::Ice::Float tilt, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setTilt(_iceI_begin_setTilt(tilt, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setTilt(::Ice::Float tilt, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setTilt(tilt, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setTilt(::Ice::Float tilt, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setTilt(tilt, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_setTilt(::Ice::Float tilt, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setTilt(tilt, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_setTilt(::Ice::Float tilt, const ::RoboCompGiraff::Callback_Giraff_setTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setTilt(tilt, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_setTilt(::Ice::Float tilt, const ::Ice::Context& context, const ::RoboCompGiraff::Callback_Giraff_setTiltPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setTilt(tilt, context, cb, cookie);
    }

    void end_setTilt(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setTilt(::Ice::Float, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompGiraff
{

class Giraff : public virtual ::Ice::Object
{
public:

    typedef GiraffPrx ProxyType;
    typedef GiraffPtr PointerType;

    virtual ~Giraff();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual ::Ice::Float decTilt(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_decTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual Botones getBotonesState(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getBotonesState(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ::Ice::Float getTilt(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ::Ice::Float incTilt(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_incTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void setTilt(::Ice::Float tilt, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_setTilt(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const Giraff& lhs, const Giraff& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const Giraff& lhs, const Giraff& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompGiraff::HardwareFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<typename S>
struct StreamWriter< ::RoboCompGiraff::HardwareFailedException, S>
{
    static void write(S* ostr, const ::RoboCompGiraff::HardwareFailedException& v)
    {
        ostr->write(v.what);
    }
};

template<typename S>
struct StreamReader< ::RoboCompGiraff::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompGiraff::HardwareFailedException& v)
    {
        istr->read(v.what);
    }
};

template<>
struct StreamableTraits< ::RoboCompGiraff::Botones>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 12;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompGiraff::Botones, S>
{
    static void write(S* ostr, const ::RoboCompGiraff::Botones& v)
    {
        ostr->write(v.Rojo);
        ostr->write(v.Verde);
        ostr->write(v.Dial);
    }
};

template<typename S>
struct StreamReader< ::RoboCompGiraff::Botones, S>
{
    static void read(S* istr, ::RoboCompGiraff::Botones& v)
    {
        istr->read(v.Rojo);
        istr->read(v.Verde);
        istr->read(v.Dial);
    }
};

}
/// \endcond

namespace RoboCompGiraff
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_decTilt.
 */
template<class T>
class CallbackNC_Giraff_decTilt : public Callback_Giraff_decTilt_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Float);

    CallbackNC_Giraff_decTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        ::Ice::Float ret;
        try
        {
            ret = proxy->end_decTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 */
template<class T> Callback_Giraff_decTiltPtr
newCallback_Giraff_decTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_decTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 */
template<class T> Callback_Giraff_decTiltPtr
newCallback_Giraff_decTilt(T* instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_decTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_decTilt.
 */
template<class T, typename CT>
class Callback_Giraff_decTilt : public Callback_Giraff_decTilt_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Float, const CT&);

    Callback_Giraff_decTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        ::Ice::Float ret;
        try
        {
            ret = proxy->end_decTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 */
template<class T, typename CT> Callback_Giraff_decTiltPtr
newCallback_Giraff_decTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_decTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_decTilt.
 */
template<class T, typename CT> Callback_Giraff_decTiltPtr
newCallback_Giraff_decTilt(T* instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_decTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_getBotonesState.
 */
template<class T>
class CallbackNC_Giraff_getBotonesState : public Callback_Giraff_getBotonesState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const Botones&);

    CallbackNC_Giraff_getBotonesState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        Botones ret;
        try
        {
            ret = proxy->end_getBotonesState(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 */
template<class T> Callback_Giraff_getBotonesStatePtr
newCallback_Giraff_getBotonesState(const IceUtil::Handle<T>& instance, void (T::*cb)(const Botones&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_getBotonesState<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 */
template<class T> Callback_Giraff_getBotonesStatePtr
newCallback_Giraff_getBotonesState(T* instance, void (T::*cb)(const Botones&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_getBotonesState<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_getBotonesState.
 */
template<class T, typename CT>
class Callback_Giraff_getBotonesState : public Callback_Giraff_getBotonesState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const Botones&, const CT&);

    Callback_Giraff_getBotonesState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        Botones ret;
        try
        {
            ret = proxy->end_getBotonesState(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 */
template<class T, typename CT> Callback_Giraff_getBotonesStatePtr
newCallback_Giraff_getBotonesState(const IceUtil::Handle<T>& instance, void (T::*cb)(const Botones&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_getBotonesState<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getBotonesState.
 */
template<class T, typename CT> Callback_Giraff_getBotonesStatePtr
newCallback_Giraff_getBotonesState(T* instance, void (T::*cb)(const Botones&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_getBotonesState<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_getTilt.
 */
template<class T>
class CallbackNC_Giraff_getTilt : public Callback_Giraff_getTilt_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Float);

    CallbackNC_Giraff_getTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        ::Ice::Float ret;
        try
        {
            ret = proxy->end_getTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 */
template<class T> Callback_Giraff_getTiltPtr
newCallback_Giraff_getTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_getTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 */
template<class T> Callback_Giraff_getTiltPtr
newCallback_Giraff_getTilt(T* instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_getTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_getTilt.
 */
template<class T, typename CT>
class Callback_Giraff_getTilt : public Callback_Giraff_getTilt_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Float, const CT&);

    Callback_Giraff_getTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        ::Ice::Float ret;
        try
        {
            ret = proxy->end_getTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 */
template<class T, typename CT> Callback_Giraff_getTiltPtr
newCallback_Giraff_getTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_getTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_getTilt.
 */
template<class T, typename CT> Callback_Giraff_getTiltPtr
newCallback_Giraff_getTilt(T* instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_getTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_incTilt.
 */
template<class T>
class CallbackNC_Giraff_incTilt : public Callback_Giraff_incTilt_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Float);

    CallbackNC_Giraff_incTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        ::Ice::Float ret;
        try
        {
            ret = proxy->end_incTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 */
template<class T> Callback_Giraff_incTiltPtr
newCallback_Giraff_incTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_incTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 */
template<class T> Callback_Giraff_incTiltPtr
newCallback_Giraff_incTilt(T* instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_incTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_incTilt.
 */
template<class T, typename CT>
class Callback_Giraff_incTilt : public Callback_Giraff_incTilt_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Float, const CT&);

    Callback_Giraff_incTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        ::Ice::Float ret;
        try
        {
            ret = proxy->end_incTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 */
template<class T, typename CT> Callback_Giraff_incTiltPtr
newCallback_Giraff_incTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_incTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_incTilt.
 */
template<class T, typename CT> Callback_Giraff_incTiltPtr
newCallback_Giraff_incTilt(T* instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_incTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_setTilt.
 */
template<class T>
class CallbackNC_Giraff_setTilt : public Callback_Giraff_setTilt_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Giraff_setTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_setTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_setTilt<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_setTilt<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Giraff_setTilt<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 * Create a wrapper instance by calling ::RoboCompGiraff::newCallback_Giraff_setTilt.
 */
template<class T, typename CT>
class Callback_Giraff_setTilt : public Callback_Giraff_setTilt_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Giraff_setTilt(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        GiraffPrx proxy = GiraffPrx::uncheckedCast(result->getProxy());
        try
        {
            proxy->end_setTilt(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T, typename CT> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_setTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T, typename CT> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_setTilt<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T, typename CT> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_setTilt<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompGiraff::Giraff::begin_setTilt.
 */
template<class T, typename CT> Callback_Giraff_setTiltPtr
newCallback_Giraff_setTilt(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Giraff_setTilt<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
