//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Giraff.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Giraff.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompGiraff::HardwareFailedException> iceC_RoboCompGiraff_HardwareFailedException_init("::RoboCompGiraff::HardwareFailedException");

const ::std::string iceC_RoboCompGiraff_Giraff_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGiraff::Giraff"
};
const ::std::string iceC_RoboCompGiraff_Giraff_ops[] =
{
    "decTilt",
    "getBotonesState",
    "getTilt",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "incTilt",
    "setTilt"
};
const ::std::string iceC_RoboCompGiraff_Giraff_decTilt_name = "decTilt";
const ::std::string iceC_RoboCompGiraff_Giraff_getBotonesState_name = "getBotonesState";
const ::std::string iceC_RoboCompGiraff_Giraff_getTilt_name = "getTilt";
const ::std::string iceC_RoboCompGiraff_Giraff_incTilt_name = "incTilt";
const ::std::string iceC_RoboCompGiraff_Giraff_setTilt_name = "setTilt";

}

RoboCompGiraff::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompGiraff::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGiraff::HardwareFailedException";
    return typeId;
}

bool
RoboCompGiraff::Giraff::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGiraff_Giraff_ids, iceC_RoboCompGiraff_Giraff_ids + 2, s);
}

::std::vector<::std::string>
RoboCompGiraff::Giraff::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompGiraff_Giraff_ids[0], &iceC_RoboCompGiraff_Giraff_ids[2]);
}

::std::string
RoboCompGiraff::Giraff::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGiraff::Giraff::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGiraff::Giraff";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_decTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    float ret = this->decTilt(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_getBotonesState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    Botones ret = this->getBotonesState(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_getTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    float ret = this->getTilt(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_incTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    float ret = this->incTilt(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_setTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_tilt;
    istr->readAll(iceP_tilt);
    inS.endReadParams();
    this->setTilt(iceP_tilt, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGiraff_Giraff_ops, iceC_RoboCompGiraff_Giraff_ops + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGiraff_Giraff_ops)
    {
        case 0:
        {
            return _iceD_decTilt(in, current);
        }
        case 1:
        {
            return _iceD_getBotonesState(in, current);
        }
        case 2:
        {
            return _iceD_getTilt(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        case 7:
        {
            return _iceD_incTilt(in, current);
        }
        case 8:
        {
            return _iceD_setTilt(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGiraff::GiraffPrx::_iceI_decTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<float>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_decTilt_name);
    outAsync->invoke(iceC_RoboCompGiraff_Giraff_decTilt_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGiraff::GiraffPrx::_iceI_getBotonesState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGiraff::Botones>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_getBotonesState_name);
    outAsync->invoke(iceC_RoboCompGiraff_Giraff_getBotonesState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGiraff::GiraffPrx::_iceI_getTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<float>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_getTilt_name);
    outAsync->invoke(iceC_RoboCompGiraff_Giraff_getTilt_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGiraff::GiraffPrx::_iceI_incTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<float>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_incTilt_name);
    outAsync->invoke(iceC_RoboCompGiraff_Giraff_incTilt_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGiraff::GiraffPrx::_iceI_setTilt(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, float iceP_tilt, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_setTilt_name);
    outAsync->invoke(iceC_RoboCompGiraff_Giraff_setTilt_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_tilt);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompGiraff::GiraffPrx::_newInstance() const
{
    return ::IceInternal::createProxy<GiraffPrx>();
}
/// \endcond

const ::std::string&
RoboCompGiraff::GiraffPrx::ice_staticId()
{
    return Giraff::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompGiraff_Giraff_decTilt_name = "decTilt";

const ::std::string iceC_RoboCompGiraff_Giraff_getBotonesState_name = "getBotonesState";

const ::std::string iceC_RoboCompGiraff_Giraff_getTilt_name = "getTilt";

const ::std::string iceC_RoboCompGiraff_Giraff_incTilt_name = "incTilt";

const ::std::string iceC_RoboCompGiraff_Giraff_setTilt_name = "setTilt";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompGiraff::HardwareFailedException> iceC_RoboCompGiraff_HardwareFailedException_init("::RoboCompGiraff::HardwareFailedException");

}

RoboCompGiraff::HardwareFailedException::HardwareFailedException(const ::std::string& what) :
    ::Ice::UserException(),
    what(what)
{
}

RoboCompGiraff::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompGiraff::HardwareFailedException::ice_id() const
{
    return "::RoboCompGiraff::HardwareFailedException";
}

RoboCompGiraff::HardwareFailedException*
RoboCompGiraff::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompGiraff::HardwareFailedException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
RoboCompGiraff::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompGiraff::HardwareFailedException", -1, true);
    ::Ice::StreamWriter< HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGiraff::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompGiraff::upCast(Giraff* p) { return p; }

void
::IceProxy::RoboCompGiraff::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Giraff>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Giraff;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompGiraff::Giraff::_iceI_begin_decTilt(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_decTilt_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGiraff_Giraff_decTilt_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGiraff_Giraff_decTilt_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGiraff_Giraff_decTilt_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Float
IceProxy::RoboCompGiraff::Giraff::end_decTilt(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGiraff_Giraff_decTilt_name);
    ::Ice::Float ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGiraff::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGiraff::Giraff::_iceI_begin_getBotonesState(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_getBotonesState_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGiraff_Giraff_getBotonesState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGiraff_Giraff_getBotonesState_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGiraff_Giraff_getBotonesState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompGiraff::Botones
IceProxy::RoboCompGiraff::Giraff::end_getBotonesState(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGiraff_Giraff_getBotonesState_name);
    ::RoboCompGiraff::Botones ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGiraff::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGiraff::Giraff::_iceI_begin_getTilt(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_getTilt_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGiraff_Giraff_getTilt_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGiraff_Giraff_getTilt_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGiraff_Giraff_getTilt_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Float
IceProxy::RoboCompGiraff::Giraff::end_getTilt(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGiraff_Giraff_getTilt_name);
    ::Ice::Float ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGiraff::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGiraff::Giraff::_iceI_begin_incTilt(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_incTilt_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGiraff_Giraff_incTilt_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGiraff_Giraff_incTilt_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGiraff_Giraff_incTilt_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Float
IceProxy::RoboCompGiraff::Giraff::end_incTilt(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGiraff_Giraff_incTilt_name);
    ::Ice::Float ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGiraff::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGiraff::Giraff::_iceI_begin_setTilt(::Ice::Float iceP_tilt, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGiraff_Giraff_setTilt_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGiraff_Giraff_setTilt_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGiraff_Giraff_setTilt_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_tilt);
        result->endWriteParams();
        result->invoke(iceC_RoboCompGiraff_Giraff_setTilt_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGiraff::Giraff::end_setTilt(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGiraff_Giraff_setTilt_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGiraff::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompGiraff::Giraff::_newInstance() const
{
    return new Giraff;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompGiraff::Giraff::ice_staticId()
{
    return ::RoboCompGiraff::Giraff::ice_staticId();
}

RoboCompGiraff::Giraff::~Giraff()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompGiraff::upCast(Giraff* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompGiraff_Giraff_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGiraff::Giraff"
};

}

bool
RoboCompGiraff::Giraff::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGiraff_Giraff_ids, iceC_RoboCompGiraff_Giraff_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompGiraff::Giraff::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompGiraff_Giraff_ids[0], &iceC_RoboCompGiraff_Giraff_ids[2]);
}

const ::std::string&
RoboCompGiraff::Giraff::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGiraff::Giraff::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGiraff::Giraff";
    return typeId;
#else
    return iceC_RoboCompGiraff_Giraff_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_decTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Ice::Float ret = this->decTilt(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_getBotonesState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    Botones ret = this->getBotonesState(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_getTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Ice::Float ret = this->getTilt(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_incTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Ice::Float ret = this->incTilt(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceD_setTilt(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_tilt;
    istr->read(iceP_tilt);
    inS.endReadParams();
    this->setTilt(iceP_tilt, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompGiraff_Giraff_all[] =
{
    "decTilt",
    "getBotonesState",
    "getTilt",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "incTilt",
    "setTilt"
};

}

/// \cond INTERNAL
bool
RoboCompGiraff::Giraff::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGiraff_Giraff_all, iceC_RoboCompGiraff_Giraff_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGiraff_Giraff_all)
    {
        case 0:
        {
            return _iceD_decTilt(in, current);
        }
        case 1:
        {
            return _iceD_getBotonesState(in, current);
        }
        case 2:
        {
            return _iceD_getTilt(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        case 7:
        {
            return _iceD_incTilt(in, current);
        }
        case 8:
        {
            return _iceD_setTilt(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompGiraff::Giraff::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Giraff, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGiraff::Giraff::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Giraff, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGiraff::_icePatchObjectPtr(GiraffPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = GiraffPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Giraff::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
