//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `RealSenseFaceID.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <RealSenseFaceID.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[2] =
{
    "::Ice::Object",
    "::RoboCompRealSenseFaceID::RealSenseFaceID"
};
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ops[] =
{
    "authenticate",
    "enroll",
    "eraseAll",
    "eraseUser",
    "getQueryUsers",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "startPreview",
    "stopPreview"
};
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name = "authenticate";
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name = "enroll";
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name = "eraseAll";
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name = "eraseUser";
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name = "getQueryUsers";
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name = "startPreview";
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name = "stopPreview";

}

bool
RoboCompRealSenseFaceID::RealSenseFaceID::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids + 2, s);
}

::std::vector<::std::string>
RoboCompRealSenseFaceID::RealSenseFaceID::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[0], &iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[2]);
}

::std::string
RoboCompRealSenseFaceID::RealSenseFaceID::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompRealSenseFaceID::RealSenseFaceID::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompRealSenseFaceID::RealSenseFaceID";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_authenticate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    UserDataList ret = this->authenticate(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_enroll(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_user;
    istr->readAll(iceP_user);
    inS.endReadParams();
    bool ret = this->enroll(::std::move(iceP_user), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_eraseAll(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->eraseAll(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_eraseUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_user;
    istr->readAll(iceP_user);
    inS.endReadParams();
    bool ret = this->eraseUser(::std::move(iceP_user), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_getQueryUsers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    UserDataList ret = this->getQueryUsers(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_startPreview(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->startPreview(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_stopPreview(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->stopPreview(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ops, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ops + 11, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ops)
    {
        case 0:
        {
            return _iceD_authenticate(in, current);
        }
        case 1:
        {
            return _iceD_enroll(in, current);
        }
        case 2:
        {
            return _iceD_eraseAll(in, current);
        }
        case 3:
        {
            return _iceD_eraseUser(in, current);
        }
        case 4:
        {
            return _iceD_getQueryUsers(in, current);
        }
        case 5:
        {
            return _iceD_ice_id(in, current);
        }
        case 6:
        {
            return _iceD_ice_ids(in, current);
        }
        case 7:
        {
            return _iceD_ice_isA(in, current);
        }
        case 8:
        {
            return _iceD_ice_ping(in, current);
        }
        case 9:
        {
            return _iceD_startPreview(in, current);
        }
        case 10:
        {
            return _iceD_stopPreview(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_authenticate(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompRealSenseFaceID::UserDataList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_enroll(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::std::string& iceP_user, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_user);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_eraseAll(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_eraseUser(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::std::string& iceP_user, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_user);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_getQueryUsers(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompRealSenseFaceID::UserDataList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_startPreview(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_iceI_stopPreview(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name);
    outAsync->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::_newInstance() const
{
    return ::IceInternal::createProxy<RealSenseFaceIDPrx>();
}
/// \endcond

const ::std::string&
RoboCompRealSenseFaceID::RealSenseFaceIDPrx::ice_staticId()
{
    return RealSenseFaceID::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name = "authenticate";

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name = "enroll";

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name = "eraseAll";

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name = "eraseUser";

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name = "getQueryUsers";

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name = "startPreview";

const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name = "stopPreview";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompRealSenseFaceID::upCast(RealSenseFaceID* p) { return p; }

void
::IceProxy::RoboCompRealSenseFaceID::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< RealSenseFaceID>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new RealSenseFaceID;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_authenticate(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompRealSenseFaceID::UserDataList
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_authenticate(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_authenticate_name);
    ::RoboCompRealSenseFaceID::UserDataList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_enroll(const ::std::string& iceP_user, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_user);
        result->endWriteParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_enroll(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_enroll_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_eraseAll(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_eraseAll(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseAll_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_eraseUser(const ::std::string& iceP_user, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_user);
        result->endWriteParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_eraseUser(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_eraseUser_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_getQueryUsers(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompRealSenseFaceID::UserDataList
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_getQueryUsers(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_getQueryUsers_name);
    ::RoboCompRealSenseFaceID::UserDataList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_startPreview(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_startPreview(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_startPreview_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_iceI_begin_stopPreview(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::end_stopPreview(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_stopPreview_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::_newInstance() const
{
    return new RealSenseFaceID;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompRealSenseFaceID::RealSenseFaceID::ice_staticId()
{
    return ::RoboCompRealSenseFaceID::RealSenseFaceID::ice_staticId();
}

RoboCompRealSenseFaceID::RealSenseFaceID::~RealSenseFaceID()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompRealSenseFaceID::upCast(RealSenseFaceID* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[2] =
{
    "::Ice::Object",
    "::RoboCompRealSenseFaceID::RealSenseFaceID"
};

}

bool
RoboCompRealSenseFaceID::RealSenseFaceID::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompRealSenseFaceID::RealSenseFaceID::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[0], &iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[2]);
}

const ::std::string&
RoboCompRealSenseFaceID::RealSenseFaceID::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompRealSenseFaceID::RealSenseFaceID::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompRealSenseFaceID::RealSenseFaceID";
    return typeId;
#else
    return iceC_RoboCompRealSenseFaceID_RealSenseFaceID_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_authenticate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    UserDataList ret = this->authenticate(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_enroll(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_user;
    istr->read(iceP_user);
    inS.endReadParams();
    bool ret = this->enroll(iceP_user, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_eraseAll(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->eraseAll(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_eraseUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_user;
    istr->read(iceP_user);
    inS.endReadParams();
    bool ret = this->eraseUser(iceP_user, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_getQueryUsers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    UserDataList ret = this->getQueryUsers(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_startPreview(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->startPreview(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceD_stopPreview(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->stopPreview(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompRealSenseFaceID_RealSenseFaceID_all[] =
{
    "authenticate",
    "enroll",
    "eraseAll",
    "eraseUser",
    "getQueryUsers",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "startPreview",
    "stopPreview"
};

}

/// \cond INTERNAL
bool
RoboCompRealSenseFaceID::RealSenseFaceID::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompRealSenseFaceID_RealSenseFaceID_all, iceC_RoboCompRealSenseFaceID_RealSenseFaceID_all + 11, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompRealSenseFaceID_RealSenseFaceID_all)
    {
        case 0:
        {
            return _iceD_authenticate(in, current);
        }
        case 1:
        {
            return _iceD_enroll(in, current);
        }
        case 2:
        {
            return _iceD_eraseAll(in, current);
        }
        case 3:
        {
            return _iceD_eraseUser(in, current);
        }
        case 4:
        {
            return _iceD_getQueryUsers(in, current);
        }
        case 5:
        {
            return _iceD_ice_id(in, current);
        }
        case 6:
        {
            return _iceD_ice_ids(in, current);
        }
        case 7:
        {
            return _iceD_ice_isA(in, current);
        }
        case 8:
        {
            return _iceD_ice_ping(in, current);
        }
        case 9:
        {
            return _iceD_startPreview(in, current);
        }
        case 10:
        {
            return _iceD_stopPreview(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompRealSenseFaceID::RealSenseFaceID::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< RealSenseFaceID, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompRealSenseFaceID::RealSenseFaceID::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< RealSenseFaceID, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompRealSenseFaceID::_icePatchObjectPtr(RealSenseFaceIDPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = RealSenseFaceIDPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(RealSenseFaceID::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
