//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: GiraffJetson.ice
//  Source: GiraffJetson.idsl
//
//******************************************************************
#ifndef ROBOCOMPGIRAFFJETSON_ICE
#define ROBOCOMPGIRAFFJETSON_ICE
module RoboCompGiraffJetson
{
	interface GiraffJetson
	{
		string getImage (bool drawSkeleton);
		string getSkeleton ();
	};
};

#endif
