//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: PathSmoother.ice
//  Source: PathSmoother.idsl
//
//******************************************************************
#ifndef ROBOCOMPPATHSMOOTHER_ICE
#define ROBOCOMPPATHSMOOTHER_ICE
module RoboCompPathSmoother
{
	struct PathPoint
	{
		float x;
		float y;
	};
	sequence <PathPoint> Path;
	interface PathSmoother
	{
		Path smoothPath (Path toSmoothPath);
	};
};

#endif
