//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `PathSmoother.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <PathSmoother.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompPathSmoother_PathSmoother_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPathSmoother::PathSmoother"
};
const ::std::string iceC_RoboCompPathSmoother_PathSmoother_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "smoothPath"
};
const ::std::string iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name = "smoothPath";

}

bool
RoboCompPathSmoother::PathSmoother::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompPathSmoother_PathSmoother_ids, iceC_RoboCompPathSmoother_PathSmoother_ids + 2, s);
}

::std::vector<::std::string>
RoboCompPathSmoother::PathSmoother::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompPathSmoother_PathSmoother_ids[0], &iceC_RoboCompPathSmoother_PathSmoother_ids[2]);
}

::std::string
RoboCompPathSmoother::PathSmoother::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompPathSmoother::PathSmoother::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompPathSmoother::PathSmoother";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompPathSmoother::PathSmoother::_iceD_smoothPath(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    Path iceP_toSmoothPath;
    istr->readAll(iceP_toSmoothPath);
    inS.endReadParams();
    Path ret = this->smoothPath(::std::move(iceP_toSmoothPath), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompPathSmoother::PathSmoother::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompPathSmoother_PathSmoother_ops, iceC_RoboCompPathSmoother_PathSmoother_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompPathSmoother_PathSmoother_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_smoothPath(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompPathSmoother::PathSmootherPrx::_iceI_smoothPath(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompPathSmoother::Path>>& outAsync, const Path& iceP_toSmoothPath, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name);
    outAsync->invoke(iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_toSmoothPath);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompPathSmoother::PathSmootherPrx::_newInstance() const
{
    return ::IceInternal::createProxy<PathSmootherPrx>();
}
/// \endcond

const ::std::string&
RoboCompPathSmoother::PathSmootherPrx::ice_staticId()
{
    return PathSmoother::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name = "smoothPath";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompPathSmoother::upCast(PathSmoother* p) { return p; }

void
::IceProxy::RoboCompPathSmoother::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< PathSmoother>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new PathSmoother;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompPathSmoother::PathSmoother::_iceI_begin_smoothPath(const ::RoboCompPathSmoother::Path& iceP_toSmoothPath, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_toSmoothPath);
        result->endWriteParams();
        result->invoke(iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompPathSmoother::Path
IceProxy::RoboCompPathSmoother::PathSmoother::end_smoothPath(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompPathSmoother_PathSmoother_smoothPath_name);
    ::RoboCompPathSmoother::Path ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompPathSmoother::PathSmoother::_newInstance() const
{
    return new PathSmoother;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompPathSmoother::PathSmoother::ice_staticId()
{
    return ::RoboCompPathSmoother::PathSmoother::ice_staticId();
}

RoboCompPathSmoother::PathSmoother::~PathSmoother()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompPathSmoother::upCast(PathSmoother* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompPathSmoother_PathSmoother_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPathSmoother::PathSmoother"
};

}

bool
RoboCompPathSmoother::PathSmoother::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompPathSmoother_PathSmoother_ids, iceC_RoboCompPathSmoother_PathSmoother_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompPathSmoother::PathSmoother::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompPathSmoother_PathSmoother_ids[0], &iceC_RoboCompPathSmoother_PathSmoother_ids[2]);
}

const ::std::string&
RoboCompPathSmoother::PathSmoother::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompPathSmoother::PathSmoother::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompPathSmoother::PathSmoother";
    return typeId;
#else
    return iceC_RoboCompPathSmoother_PathSmoother_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompPathSmoother::PathSmoother::_iceD_smoothPath(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    Path iceP_toSmoothPath;
    istr->read(iceP_toSmoothPath);
    inS.endReadParams();
    Path ret = this->smoothPath(iceP_toSmoothPath, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompPathSmoother_PathSmoother_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "smoothPath"
};

}

/// \cond INTERNAL
bool
RoboCompPathSmoother::PathSmoother::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompPathSmoother_PathSmoother_all, iceC_RoboCompPathSmoother_PathSmoother_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompPathSmoother_PathSmoother_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_smoothPath(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompPathSmoother::PathSmoother::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< PathSmoother, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompPathSmoother::PathSmoother::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< PathSmoother, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompPathSmoother::_icePatchObjectPtr(PathSmootherPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = PathSmootherPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(PathSmoother::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
