//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `MoveTowards.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <MoveTowards.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompMoveTowards_MoveTowards_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMoveTowards::MoveTowards"
};
const ::std::string iceC_RoboCompMoveTowards_MoveTowards_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "move"
};
const ::std::string iceC_RoboCompMoveTowards_MoveTowards_move_name = "move";

}

bool
RoboCompMoveTowards::MoveTowards::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMoveTowards_MoveTowards_ids, iceC_RoboCompMoveTowards_MoveTowards_ids + 2, s);
}

::std::vector<::std::string>
RoboCompMoveTowards::MoveTowards::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompMoveTowards_MoveTowards_ids[0], &iceC_RoboCompMoveTowards_MoveTowards_ids[2]);
}

::std::string
RoboCompMoveTowards::MoveTowards::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMoveTowards::MoveTowards::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompMoveTowards::MoveTowards";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompMoveTowards::MoveTowards::_iceD_move(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_x;
    float iceP_y;
    float iceP_alpha;
    istr->readAll(iceP_x, iceP_y, iceP_alpha);
    inS.endReadParams();
    Command ret = this->move(iceP_x, iceP_y, iceP_alpha, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompMoveTowards::MoveTowards::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMoveTowards_MoveTowards_ops, iceC_RoboCompMoveTowards_MoveTowards_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMoveTowards_MoveTowards_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_move(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMoveTowards::MoveTowardsPrx::_iceI_move(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompMoveTowards::Command>>& outAsync, float iceP_x, float iceP_y, float iceP_alpha, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompMoveTowards_MoveTowards_move_name);
    outAsync->invoke(iceC_RoboCompMoveTowards_MoveTowards_move_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_x, iceP_y, iceP_alpha);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompMoveTowards::MoveTowardsPrx::_newInstance() const
{
    return ::IceInternal::createProxy<MoveTowardsPrx>();
}
/// \endcond

const ::std::string&
RoboCompMoveTowards::MoveTowardsPrx::ice_staticId()
{
    return MoveTowards::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompMoveTowards_MoveTowards_move_name = "move";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompMoveTowards::upCast(MoveTowards* p) { return p; }

void
::IceProxy::RoboCompMoveTowards::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< MoveTowards>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new MoveTowards;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompMoveTowards::MoveTowards::_iceI_begin_move(::Ice::Float iceP_x, ::Ice::Float iceP_y, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompMoveTowards_MoveTowards_move_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompMoveTowards_MoveTowards_move_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompMoveTowards_MoveTowards_move_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_x);
        ostr->write(iceP_y);
        ostr->write(iceP_alpha);
        result->endWriteParams();
        result->invoke(iceC_RoboCompMoveTowards_MoveTowards_move_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompMoveTowards::Command
IceProxy::RoboCompMoveTowards::MoveTowards::end_move(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompMoveTowards_MoveTowards_move_name);
    ::RoboCompMoveTowards::Command ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompMoveTowards::MoveTowards::_newInstance() const
{
    return new MoveTowards;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompMoveTowards::MoveTowards::ice_staticId()
{
    return ::RoboCompMoveTowards::MoveTowards::ice_staticId();
}

RoboCompMoveTowards::MoveTowards::~MoveTowards()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompMoveTowards::upCast(MoveTowards* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompMoveTowards_MoveTowards_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMoveTowards::MoveTowards"
};

}

bool
RoboCompMoveTowards::MoveTowards::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompMoveTowards_MoveTowards_ids, iceC_RoboCompMoveTowards_MoveTowards_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompMoveTowards::MoveTowards::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompMoveTowards_MoveTowards_ids[0], &iceC_RoboCompMoveTowards_MoveTowards_ids[2]);
}

const ::std::string&
RoboCompMoveTowards::MoveTowards::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompMoveTowards::MoveTowards::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompMoveTowards::MoveTowards";
    return typeId;
#else
    return iceC_RoboCompMoveTowards_MoveTowards_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompMoveTowards::MoveTowards::_iceD_move(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_x;
    ::Ice::Float iceP_y;
    ::Ice::Float iceP_alpha;
    istr->read(iceP_x);
    istr->read(iceP_y);
    istr->read(iceP_alpha);
    inS.endReadParams();
    Command ret = this->move(iceP_x, iceP_y, iceP_alpha, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompMoveTowards_MoveTowards_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "move"
};

}

/// \cond INTERNAL
bool
RoboCompMoveTowards::MoveTowards::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompMoveTowards_MoveTowards_all, iceC_RoboCompMoveTowards_MoveTowards_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompMoveTowards_MoveTowards_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_move(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompMoveTowards::MoveTowards::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< MoveTowards, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompMoveTowards::MoveTowards::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< MoveTowards, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompMoveTowards::_icePatchObjectPtr(MoveTowardsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = MoveTowardsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(MoveTowards::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
