//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Follower.ice
//  Source: Follower.idsl
//
//******************************************************************
#ifndef ROBOCOMPFOLLOWER_ICE
#define ROBOCOMPFOLLOWER_ICE
module RoboCompFollower
{
	interface Follower
	{
		void setState (bool state);
	};
};

#endif
