//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: SoundRotationPub.ice
//  Source: SoundRotationPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPSOUNDROTATIONPUB_ICE
#define ROBOCOMPSOUNDROTATIONPUB_ICE
module RoboCompSoundRotationPub
{
	struct Position
	{
		float elevation;
		float azimut;
		float x;
		float y;
		float z;
	};
	sequence <Position> positions;
	interface SoundRotationPub
	{
		void getAngle (float ang);
		void getKeyWord (string word);
		void getPositions (positions pos);
		void personFound (bool found);
	};
};

#endif
