//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: SoundRotation.ice
//  Source: SoundRotation.idsl
//
//******************************************************************
#ifndef ROBOCOMPSOUNDROTATION_ICE
#define ROBOCOMPSOUNDROTATION_ICE
module RoboCompSoundRotation
{
	struct Position
	{
		float elevation;
		float azimut;
		float x;
		float y;
		float z;
	};
	sequence <Position> positions;
	interface SoundRotation
	{
		void getAngle (float ang);
		void getKeyWord (string word);
		void getPositions (positions pos);
		void personFound (bool found);
	};
};

#endif
