//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Recorder.ice
//  Source: Recorder.idsl
//
//******************************************************************
#ifndef ROBOCOMPRECORDER_ICE
#define ROBOCOMPRECORDER_ICE
module RoboCompRecorder
{
	interface Recorder
	{
		bool recording (bool rec);
	};
};

#endif
